import featurePackage from "../featurePackage";
const fs = require("fs");
describe("Autogenerated FeaturePackage sanity tests",()=> {

    it("package is array", () => {
        expect(Array.isArray(featurePackage)).toBeTruthy();
    })
    it("package is array of componentPackages", () => {
        featurePackage.forEach(pack => {
            const componentPackage = pack.componentPackage;
            expect(componentPackage).toBeTruthy();
        })
    })
    it("every package has atleast a component and destination", () => {
        featurePackage.forEach(pack => {
            const componentPackage = pack.componentPackage;
            expect(componentPackage.component).toBeTruthy();
            expect(componentPackage.destinationFeaturePoint).toBeTruthy();

        })
    })
    it("if componentPackage has decorators the decorators object is an array", () => {
        featurePackage.forEach(pack => {
            const componentPackage = pack.componentPackage;
            if (componentPackage.decorators) {
                    expect(Array.isArray(componentPackage.decorators)).toBeTruthy();
            }
        })
    })
    it("if componentPackage has decorators each is of the form {name,props}", () => {
        featurePackage.forEach(pack => {
            const componentPackage = pack.componentPackage;
            if (componentPackage.decorators) {
                componentPackage.decorators.forEach(decorator => {
                    expect(decorator.name).toBeTruthy();
                    expect(decorator.props).toBeTruthy();
                })
            }
        })
    })
    it("every decorator is registered in decorators.json",()=>{
        const decoratorNames = [];
        featurePackage.forEach(pack => {
            const componentPackage = pack.componentPackage;
            if(componentPackage.decorators){
                componentPackage.decorators.forEach(dec =>decoratorNames.push(dec.name));
            }
        })

        if (decoratorNames.length>0){
            // const exists = fs.existsSync("../decorators.json")
            let decorators;
            try {
                decorators = require.resolve("../decorators.json")
            }catch(e){
                decorators = false;
            }
            expect(decorators).toBeTruthy();
            if(decorators){
                const registeredDecorators = require("../decorators.json")
                decoratorNames.forEach(usedName=>{
                    expect(registeredDecorators[usedName]).toBeTruthy();
                })
            }
        }
    })
});